apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: csi-moosefs-config
data:
  master_host: "192.168.40.0"           # domain name is recommended, this IP is only an example
  master_port: "19421"
# master_host: "172.17.2.80"
# master_port: "9421"
  k8s_root_dir: "/"                     # MooseFS root directory for all claims within this Kubernetes cluster
  driver_working_dir: "pv_data"         # MooseFS directory (relative to csi_root_dir) for all driver data
                                        # (effective working dir will be calculated as k8s_root_dir/driver_working_dir)
  mount_count: "1"                      # Number of pre-created MooseFS mounts on each node
  mfs_logging: "true"                   # Should driver log to k8s_root_dir/driver_working_dir/logs directory
